apiVersion: apps/v1
kind: Deployment
metadata:
  name: fyro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: duffer-api
  template:
    metadata:
      labels:
        app: duffer-api
        version: IMAGE_LABEL
    spec:
      containers:
      - name: duffer-api
        image: ACR_URL/duffer-api:IMAGE_LABEL
        ports:
        - containerPort: 80
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: duffer-api
spec:
  type: NodePort
  selector:
    app: duffer-api
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: duffer-api
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  # https://docs.microsoft.com/en-us/azure/aks/http-application-routing
  - host: duffer-api.AKS_URL
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: duffer-api
            port:
              number: 80
